### ISSUE TITLE
[Core] Define XML schema

### ISSUE THREAD

**Issue by fbiville** [fbiville/liquigraph#10]
... thus preventing users from typos and helping them with autocompletion and this kind of goodies.

**Comment by sim51** [comment]
Java implementation is OK, I have to make a better XSD (specially with precondition)

**Comment by sim51** [comment]
I thinks it's good now, but it must be tested with some more complex changelogs

**Comment by fbiville** [comment]
Finally merged :)
I re-worked the PR a tiny bit so that it worked well with the import pre-processing that had been done in parallel and merged beforehand.

Great job @sim51, thanks!
