### ISSUE TITLE
Embedded connection to the database

### ISSUE THREAD

**Issue by frosiere** [fbiville/liquigraph#107]
Hello,

First of all, thanks for the great job you made on the migration process.

In the description, I don't see anything to connect an embedded database?

Can you tell me how I could do using the last version of the tool?

Best regards,

François

**Comment by fbiville** [comment]
Hi, thanks for the kind words. 
You can simply set the URI to `jdbc:neo4j:mem:$NAME_OF_DB`.

**Comment by fbiville** [comment]
If you like, you could improve the latest documentation [here](https://github.com/fbiville/liquigraph/blob/gh-pages/latest/index.html).

**Comment by fbiville** [comment]
If you don't think it solved your issue, feel free to reopen this.
