### ISSUE TITLE
Complete 2.0.0 and 3.0.0 releases

### ISSUE THREAD

**Issue by fbiville** [fbiville/liquigraph#111]
- [x]  Complete https://github.com/fbiville/liquigraph/releases (FB)
 - Update https://github.com/fbiville/liquigraph/tree/gh-pages (FP)
     - [x] copy XML schema to a 1.0(?) folder and update doc examples
     - [x] copy `latest` to `2.0` and `3.0` (only `latest` should be indexed)
     - [x] generate Maven plugin site for 2.0.0 and 3.0.0 and update respective links in the documentation
 - Update https://github.com/fbiville/homebrew-liquigraph (FB)
    - [ ] for 2.0.0
    - [x] for 3.0.0
 - [x] Announce in neo4j-users Slack (FP)
 - [x] Neo4j ecosystem ML (FB)

**Comment by fpavageau** [comment]
For consistency, I guess the documentation directories should be `2.0.0` and `3.0.0`, not `2.0` and `3.0`, or we'll lose the previous documentation when releasing new versions for bug fixes.

**Comment by fbiville** [comment]
It's probably a bit early to tell, but do we need that granularity?

**Comment by fbiville** [comment]
Anyway, for now, you're right, let's have a `2.0.0` and `3.0.0`.
We'll wait and see whether it becomes overkill or not.

**Comment by fbiville** [comment]
Still some back and forth with Homebrew but we're getting there!

 - https://github.com/Homebrew/homebrew-core/pull/509 (3.0.0)
 - https://github.com/Homebrew/homebrew-versions/pull/1377 (2.0.0)

@fpavageau by the way, we should include the XML schema again in the documentation examples.

**Comment by fpavageau** [comment]
@fbiville You mean before the detailed section, right? I added it to the first complete example [there](https://fbiville.github.io/liquigraph/3.0.0/index.html#detailed_section) but after all, maybe it should also be added to the first example.

**Comment by fbiville** [comment]
Yep, before the detailed section.

**Comment by fpavageau** [comment]
I've added the XML schema to the first example.

**Comment by fbiville** [comment]
Homebrew for Liquigraph 3.0.0 is done \o/
Ongoing discussion for Liquigraph 2.0.0: https://github.com/Homebrew/homebrew-versions/pull/1377.

**Comment by fbiville** [comment]
I'll open a separate issue for Homebrew / Liquigraph 2.0.
This requires more work and is not entirely related to the release.
