### ISSUE TITLE
Fix the JDK requirements

### ISSUE THREAD

**Issue by fpavageau** [fbiville/liquigraph#112]
`master` doesn't currently build when using JDK 7 (some tests fail due to package-private test classes), but that really should be the target.

`master_3.x` only requires JDK 7, but probably needs JDK 8 because of the Neo4j JDBC driver: the build seems to pass when using JDK 7, but the tests in `liquigraph-core` don't actually run at all (silently).

**Comment by fbiville** [comment]
Yep, let's `enforce` this ;-)

**Comment by fpavageau** [comment]
Regarding `master`, the build passes with Oracle JDK 1.7u80 (used by Travis CI) but not with previous versions (1.7u75 and 1.7u72 on my machine), so I guess I'll fix the test classes anyway: the problem is with public classes extending a package-private super class, which makes JUnit fail with

> java.lang.IllegalAccessException: Class org.junit.runners.model.FrameworkMethod$1 can not access a member of class org.liquigraph.core.io.ChangelogGraphWriterTestSuite with modifiers "public"

It's simple enough to fix, even if the Travis CI build won't see any regression that might be introduced later. It's one less barrier to building the project on your own. I had forgotten to upgrade my JDK 7 to the ultimate release, I'm probably not alone.

**Comment by fpavageau** [comment]
Everything should be up-to-date now:

  - JDK 7 for `master`
  - JDK 8 for `master_3.x`, with the documentation updated
