### ISSUE TITLE
Tests fail when run with some locales

### ISSUE THREAD

**Issue by pasqualeorsini** [fbiville/liquigraph#139]
Almost all the tests methods of XmlSchemaValidatorTest fail when run on a system with the following locales :
- French
- German
- Japanese
- Simplified Chinese
- Korean

The tests are comparing the expected error messages with error messages localized in english. 
When the error messages are localized the asserts fail.

**Comment by fbiville** [comment]
Thanks a lot for your fix! LGTM
I think it's not the first time we had this issue and we somehow lost the fix in between.

**Comment by fbiville** [comment]
Now fixed, thanks!
