### ISSUE TITLE
[Core] Support migration from a GraphDatabaseService instance

### ISSUE THREAD

**Issue by YoannBuch** [fbiville/liquigraph#141]
When my application starts, it creates a `GraphDatabaseService` instance. Right after creation I'd like to use Liquigraph to run some migration logic on that instance.

It looks like it's supported by the JDBC driver:

> Connect with URLs on the form jdbc:neo4j:instance:name, e.g. jdbc:neo4j:instance:mydb and put the GraphDatabaseService object instance under the same name into the properties provided to the driver

The `ConfigurationBuilder` could offer a way to set the properties:

```
Configuration configuration = new ConfigurationBuilder()
                .withMasterChangelogLocation("changelog.xml")
                .withUri(String.format("jdbc:neo4j:instance:dbName))
                .withDriverProperties(properties)
                .withRunMode()
                .build();
```

Eventually these properties would passed to [DriverManager.html.getConnection()](https://docs.oracle.com/javase/7/docs/api/java/sql/DriverManager.html#getConnection(java.lang.String,%20java.util.Properties)), probably [here](https://github.com/fbiville/liquigraph/blob/67ba6ef7bf03b09a7e7ef204898da9fdce978bfc/liquigraph-core/src/main/java/org/liquigraph/core/configuration/ConnectionConfigurationByUri.java#L80).

**Comment by YoannBuch** [comment]
Note that I initially tried this before creating the instance of `GraphDatabaseService`: 

```
Configuration configuration = new ConfigurationBuilder()
                .withMasterChangelogLocation("changelog.xml")
                .withUri("jdbc:neo4j:file:pathToMyDb")
                .withRunMode()
                .build();
```

It doesn't work for my use case because we can't have multiple connections to a neo4j embedded database. The database is used by Liquigraph and it is never shutdown (I think it only shutdowns when the JVM exits).

**Comment by fbiville** [comment]
@YoannBuch what about introducing `withGraphDatabaseService(GraphDatabaseService)`? it would encapsulate the JDBC driver plumbing.

**Comment by YoannBuch** [comment]
Even better!

How do you want to go about this? Should I submit a PR?

**Comment by fbiville** [comment]
That would be awesome! :D

**Comment by fbiville** [comment]
Thanks a lot for your great work! 👍

**Comment by YoannBuch** [comment]
Thanks for reviewing and merging that fast!

Please keep me updated when you create a new release.

**Comment by fbiville** [comment]
@YoannBuch now released. Should be soon enough in Maven Central :-)

**Comment by YoannBuch** [comment]
Awesome, thank you!!
