### ISSUE TITLE
[Core] Liquigraph crashes when trying to change schema (add index / create constraint)

### ISSUE THREAD

**Issue by lilianaziolek** [fbiville/liquigraph#40]
I have a very simple changeset, just containing a single index.
```xml
<changelog>
	<changeset id="initial-indexes" author="lili">
        <query>CREATE INDEX ON :Foo(name)</query>
	</changeset>
</changelog>
```
When trying to run it with liquigraph 1.0.0.RC2 on a clean localhost instance of neo4j 2.2.1 it crashes with an exception:
```java
Caused by: java.lang.RuntimeException: Error executing cypher statement(s) [{code=Neo.ClientError.Transaction.InvalidType, message=Cannot perform schema updates in a transaction that has performed data updates.}]
```
However, if I change the CREATE INDEX to something not modifying the schema, e.g. CREATE a node, then it loads fine. Looks to me that liquigraph would need to use separate transactions for creating indexes and updating its own data. I have no other queries in the changeset so I assume it's the changeset-tracking data that's being inserted within the same transaction.

**Comment by fbiville** [comment]
Thanks for the report, we'll look into it.

**Comment by fbiville** [comment]
Bingo: https://github.com/fbiville/liquigraph/blob/master/liquigraph-core/src/main/java/org/liquigraph/core/writer/ChangelogGraphWriter.java#L51.

I will push a fix this week.

**Comment by lilianaziolek** [comment]
Fabulous! thanks a lot! I'll be going on holiday soon so no rush, I'll test
it again when I'm back in June :)

**Comment by mbyrne00** [comment]
Hi @fbiville. Just saw this great tool and looking at incorporating it into our project. This fix and https://github.com/fbiville/liquigraph/issues/23 would be great to include - any idea when RC3 might be ready to cut?

**Comment by fbiville** [comment]
@mbyrne00 RC3 will hopefully be out within the next 2 weeks. Would that timing suit you?

**Comment by mbyrne00** [comment]
That would be great! In the mean time when #23 has been merged into master we could build snapshot locally and give it a rest to provide feedback.

**Comment by fbiville** [comment]
@mbyrne00 #23 is a bit unsatisfactory at that point, because there is still a time window during which a concurrent execution may happen, as described here: https://groups.google.com/forum/?hl=en-GB#!topic/neo4j/28t4xOlhGLg.

We can still merge it now and improve it later.

**Comment by mbyrne00** [comment]
Yea it would be great to have what's there to date. I'd like to give it a test and look under the covers. Thanks!

**Comment by fbiville** [comment]
Fixed in master.
