### ISSUE TITLE
[Core] Multiple queries per changeset

### ISSUE THREAD

**Issue by heroicefforts** [fbiville/liquigraph#44]
Is there a technical reason that you cannot define multiple queries per changeset?  I assume that a changeset is run in a transaction.

**Comment by fbiville** [comment]
Thanks for the feedback.
What is your usecase? You do not have any way to rewrite your queries to a single one?
Having multiple queries per changeset is feasible, though. I'm open for discussion ;-)

**Comment by heroicefforts** [comment]
I was thinking in terms of logically grouping sets of DDL statements together, mainly for readability.  For example, cypher doesn't seem to allow chaining multiple constraint statements.

**Comment by fbiville** [comment]
Sounds legit, I'll look into it, unless you are willing to submit a pull request :)

**Comment by fbiville** [comment]
Done :)
