### ISSUE TITLE
Sequential migration runs fail when using context.

### ISSUE THREAD

**Issue by heroicefforts** [fbiville/liquigraph#45]
Assuming that I'm understanding the use case for contexts, it appears that there's a bug in the PersistedChangesetValidator.  Basically, if you run a migration with context, then only the invoked changesets are persisted.  On a subsequent run the validator is comparing the index of the persisted value against the index of the complete changelog, so they never match and migration always fails.  

Perhaps, the absolute index of the changeset should be stored in the graph and then compared against the absolute index of the changelog list.

**Comment by fbiville** [comment]
Thanks for reporting this. I'll look into this, unless you are willing to submit a pull request ;-)

**Comment by heroicefforts** [comment]
I may be able to take a look after the holiday.  Do you think storing the absolute index is the proper solution?

On November 25, 2015 4:48:25 AM EST, "@fbiville" <notifications@github.com> wrote:
>Thanks for reporting this. I'll look into this, unless you are willing
>to submit a pull request ;-)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fbiville/liquigraph/issues/45#issuecomment-159552552

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by fbiville** [comment]
I'll take a thorough look this week and re-evaluate the best approach based on your initial feedback. Thanks!

**Comment by fbiville** [comment]
In my opinion, this is a bug lying around this line: https://github.com/fbiville/liquigraph/blob/master/liquigraph-core/src/main/java/org/liquigraph/core/api/MigrationRunner.java#L67.

Either `ChangelogReader` should accept an instance of `ExecutionContexts` as argument or `PersistedChangesetValidator` should filter the changesets.

I would personally favor the first approach as this is, imo, not the responsibility of the validator to know about execution contexts.

**Comment by fbiville** [comment]
Now regarding the approach with absolute indices, unless I'm missing something, this should work just fine. Given Liquigraph is an *incremental* migration runner, indices should only grow (new changesets have to appended).

WDYT @heroicefforts?

**Comment by heroicefforts** [comment]
Is the expectation that one and only one context set will ever be configured for a given database?  

In the above case, the filtering needs to be done on the declared changesets before the comparison.

**Comment by fbiville** [comment]
I indeed had in mind: 1 configuration per target database. 
Does your usecase require something else? 

One counterargument would be the case of graph DB containing several distinct graphs. I may be wrong, but this seems like a marginal use.

**Comment by heroicefforts** [comment]
Do you think you could shoot me an email?  I have some further ideas on this and another question.  My email info is in my GH profile.

**Comment by fbiville** [comment]
Sure :)

**Comment by fbiville** [comment]
The problem arises in the following context:

> If both committers work on their local instance, and Liquigraph has been initially at state : (A)->(B)
>
> Committer 1 : (A)->(B)->(C)
> Committer 2 : (A)->(B)->(D)
>
> If committer 2 is merged last, Liquigraph changelog will look like (A)->(B)->(C)->(D) which won't be a problem on Committer 1 Neo4j instance but may fail on Committer 2 instance.

Liquigraph validation tries to be too smart.
I'll just simplify it, leaving more power (and responsibility ;-)) to the user.

**Comment by fbiville** [comment]
@heroicefforts I've simply removed the ordering constraints as it is too restrictive.
This is now available on `master` for your feedback :-)
