### ISSUE TITLE
Changesets with multiple queries are not calculating the right checksum.

### ISSUE THREAD

**Issue by pointwisefixed** [fbiville/liquigraph#56]
If you write a changeset with multiple queries (in my tests I had 2 queries) liquigraph will run fine the first time but if you rerun it, it throws an exception when calculating the queries checksum. I believe it's because the order the queries are being retrieved matter to calculate the checksum:

`MATCH (changelog:__LiquigraphChangelog)<-[exec:EXECUTED_WITHIN_CHANGELOG]-(changeset:__LiquigraphChangeset) WITH changeset, exec MATCH (changeset)<-[:EXECUTED_WITHIN_CHANGESET]-(query:__LiquigraphQuery) WITH changeset, query, exec ORDER BY exec.time ASC, query.order ASC WITH changeset, COLLECT(query.query) AS queries, exec RETURN {   id: changeset.id,    author:changeset.author,    checksum:changeset.checksum,    query:queries} AS changeset`

is used in ChangelogGraphReader but the expression `query.order ASC` is moot as we are not currently storing that (at least the xsd doesn't allow it as QueryType is a simple string). This can cause indeterministic behavior when calculating the checksums.

**Comment by fbiville** [comment]
Nice catch, thanks for the report. 👍 

There is indeed an inconsistency between the [reader](https://github.com/fbiville/liquigraph/blob/master/liquigraph-core/src/main/java/org/liquigraph/core/io/ChangelogGraphReader.java#L40) and the [writer](https://github.com/fbiville/liquigraph/blob/master/liquigraph-core/src/main/java/org/liquigraph/core/io/ChangelogGraphWriter.java#L55).

We should use the `order` attribute of `EXECUTED_WITHIN_CHANGESET ` relation.

Do you want to push a fix? :-)

**Comment by pointwisefixed** [comment]
Sure I can, I'll create a pr soon!

**Comment by fbiville** [comment]
Very nice, looking forward to merging it! :-)

**Comment by pointwisefixed** [comment]
Done! let me know if I did anything wrong or if you have comments on my changes.

**Comment by fbiville** [comment]
Pull request is merged, feel free to test against the latest SNAPSHOT!

**Comment by pointwisefixed** [comment]
Verified that it works. Thanks for merging and your work on maintaining this awesome library.

**Comment by fbiville** [comment]
Thanks for your contributions!
