### ISSUE TITLE
Invalid persistence of executed changesets with run-on-change/run-always

### ISSUE THREAD

**Issue by fpavageau** [fbiville/liquigraph#58]
Liquigraph can only be run twice with the following changelog:
```xml
<changelog>
  <changeset id="create-node" run-always="true">
    <query>CREATE (n:Node)</query>
  </changeset>
</changelog>
```

The first time, it will record the execution with a `MERGE` query equivalent to:
```
MATCH (changelog:__LiquigraphChangelog)
CREATE (changelog)<-[:EXECUTED_WITHIN_CHANGELOG {order: 1}]-(:__LiquigraphChangeset {id: "create-node"})
```
(other properties of the changeset omitted). All is well.

The second time, due to the presence of the `order` property *inside* the `MERGE` clause, it will record *another* execution, despite the method being called ["upsert"](https://github.com/fbiville/liquigraph/blob/liquigraph-1.0.RC2/liquigraph-core/src/main/java/org/liquigraph/core/writer/ChangelogGraphWriter.java#L89):
```
MATCH (changelog:__LiquigraphChangelog)
CREATE (changelog)<-[:EXECUTED_WITHIN_CHANGELOG {order: 2}]-(:__LiquigraphChangeset {id: "create-node"})
```

If you try to run Liquibase a third time, it will [complain](https://github.com/fbiville/liquigraph/blob/liquigraph-1.0.RC2/liquigraph-core/src/main/java/org/liquigraph/core/validation/PersistedChangesetValidator.java#L52-56) that you have less declared changesets than have been executed (persisted).

I think the fix is actually simple. Instead of
```
MATCH (changelog:__LiquigraphChangelog)
MERGE (changelog)<-[:EXECUTED_WITHIN_CHANGELOG {order: {1}}]-(changeset:__LiquigraphChangeset {id: {2}})
ON MATCH SET  changeset.checksum = {3},
              changeset.query = {4}
ON CREATE SET changeset.author = {5},
              changeset.query = {4}
              changeset.checksum = {3}
```
the [`CHANGESET_UPSERT`](https://github.com/fbiville/liquigraph/blob/liquigraph-1.0.RC2/liquigraph-core/src/main/java/org/liquigraph/core/writer/ChangelogGraphWriter.java#L23) query should be
```
MATCH (changelog:__LiquigraphChangelog)
MERGE (changelog)<-[exec:EXECUTED_WITHIN_CHANGELOG]-(changeset:__LiquigraphChangeset {id: {2}})
ON MATCH SET  changeset.checksum = {3},
              changeset.query = {4}
ON CREATE SET changeset.author = {5},
              changeset.query = {4}
              changeset.checksum = {3},
              exec.order = {1}
```
(not tested at all, though, but it's the gist of the fix).

I'll try preparing a pull request.

**Comment by fbiville** [comment]
Cool, thx for the report (and the future fix)!

**Comment by fbiville** [comment]
I guess we can close this ;-)

**Comment by fpavageau** [comment]
Definitely, if I'd checked master before filing the issue, I would have seen it was already fixed.
