### ISSUE TITLE
Support Bolt (Neo4j 3.0.0)

### ISSUE THREAD

**Issue by fbiville** [fbiville/liquigraph#62]

**Comment by pointwisefixed** [comment]
@fbiville I can help with this if you want. It will be of great benefit to my team as we will eventually upgrade too.  What do you think are the main things to look out for during this update? if any that you know.

**Comment by fbiville** [comment]
The first approach is to directly open a PR that adds the version to `.travis.yml` with the latest 3.0.0 RC.
You can then see how the build behaves on Travis CI.

You could also directly change `neo4j.version` to point to the good release candidate.

I expect specific dependency problems (as happened with 2.2.x and 2.3.x) and maybe some JDBC driver issues.

**Comment by pointwisefixed** [comment]
Started working on this and found a blocker (neo4j-jdbc) which actually doesn't support neo4j 3.0 as far as I can tell. Created a ticket in neo4j-jdbc to ask them about it.

**Comment by fbiville** [comment]
Thanks! Meanwhile, I will ping for more information on Neo4j Slack.

**Comment by fbiville** [comment]
It's not gonna be easy, this is an entirely new project: http://www.larus-ba.it/en/blog/2016/03/01/neo4j-jdbc-3x-bolt-en/. 

I guess we'll have to maintain two different Liquigraph: one for v2, one for v3.

Better ideas most welcome...

**Comment by pointwisefixed** [comment]
@fbiville I knew about the binary drivers, I didn't know they were gonna stop supporting the rest API after v3.0. I wonder if writing a facade module around neo4j that lets us switch versions would be feasible.

**Comment by fbiville** [comment]
@pointwisefixed that could be worth a try, but that might turn out very complex.

**Comment by fbiville** [comment]
@pointwisefixed by the way, it would be worth considering changing the codebase in a more impactful way. Neo4j 3.0 offers stored procedures, which could turn out to be very helpful for Liquigraph context!

**Comment by pointwisefixed** [comment]
@fbiville I gotta say those stored procedure look kind of neat in Neo4j 3.x, I just noticed that neo4j-ogm is doing the abstraction thing to be able to support multiple neo4j versions and connection modes (embedded, http, or the new bolt protocol). I think I will use that approach and create a PR. Give me some time as sometimes work gets in the way :)

**Comment by fbiville** [comment]
Sounds good!

**Comment by mvitz** [comment]
FYI: I tested our application with the current SNAPSHOT and Neo4j 3.0.0 and it worked without any problems till now.

**Comment by fbiville** [comment]
@mvitz nice to know, thanks for the test!
We'll need a specific support for Bolt, though.

**Comment by mvitz** [comment]
Just as a hint, I tried using Liquigraph with the new neo4j-jdbc-bolt driver. Problems I found so far:
* setObject isn't implemented their currently
* the validation for the uri in `MandatoryOptionValidator` must be expanded or dropped (I personally think there is no need to check this, if the user supplies a wrong JDBC URI he will fail still very early and this check just blocks newer schemas ;-) )
* The Class.forName call's aren't working any longer as the the old driver isn't in the classpath any longer
* The driver is more strict in regards of the raw query strings. Therefore the {1} syntax which isn't JDBC (but cypher) isn't working any longer. In all queries these needs to be replaced with ? and if a parameter was used more than once it need to be set into the PreparedStatement multiple times

Hope this helps :-)

**Comment by fbiville** [comment]
Nice, thanks for the heads-up! 👍

**Comment by mvitz** [comment]
Next update ;-)

* my last point was fixed with https://github.com/neo4j-contrib/neo4j-jdbc/commit/b0890d335b4c798148fc31325dee50ca06aeca23
* For setObject I will provide a PR to neo4j ;-)

**Comment by fbiville** [comment]
Great to hear, thanks a lot for your efforts!

**Comment by fbiville** [comment]
@mvitz by the way, do not hesitate to share your work in a PR, even if it's not 100% functional yet ;-)

**Comment by mvitz** [comment]
;-) I have a working version you can view at in #84

**Comment by fbiville** [comment]
@mvitz I think we can have a separate branch for 3.0.x with its own release cycles. 
The goal is still to be as consistent as possible with the main branch: feel free, though, to remove any code unsupported by the new JDBC driver (like embedded mode e.g.).

**Comment by fbiville** [comment]
Now fixed. Thanks a lot @mvitz. The branch is [`master_3.x`](https://github.com/fbiville/liquigraph/tree/master_3.x).
