### ISSUE TITLE
Criteria for changeset unicity

### ISSUE THREAD

**Issue by fpavageau** [fbiville/liquigraph#63]
The documentation says:

> Finally, a changeset is uniquely identified within the changelog by its mandatory ID and author attributes.

However, the queries are only based on the `id`, so the documentation should probably be fixed.

Moreover, the minimum Neo4j version seems to be 2.0.x (though the documentation does not mention it explicitly, and should also be fixed for that as well 😄), which already supports [uniqueness constraints](http://neo4j.com/docs/2.0.5/query-constraints.html). I think it might be a good idea to add such a constraint on `__LiquigraphChangeset.id`, which would have prevented the "corruption" I got when I stumbled on #58.

**Comment by fbiville** [comment]
Documentation is right, implementation is wrong :-)
Want to push a PR that ensures a unicity constraint on id/author? :-)

**Comment by fpavageau** [comment]
OK, that solves the question about the uniqueness constraint, since it's only per property.

I'll have a look at the queries once I'm done with #58.

**Comment by fbiville** [comment]
Great job, thanks again!
