### ISSUE TITLE
Use of the -p flag

### ISSUE THREAD

**Issue by airomega** [fbiville/liquigraph#73]
We're running a multiple dockerized Neo4J instances which contain a small set of identical data. We'd like to add the data at the Neo4J container launch. We dockerized liquigraph to run alongside the Neo4J container launch however the -p flag doesn't appear to work. This means we can't add data without manual intervention to key the password. 

Is it possible to use the -p flag?

```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'password' but no main parameter was defined
	at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:914)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:759)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.<init>(JCommander.java:210)
	at org.liquigraph.cli.LiquigraphCli.main(LiquigraphCli.java:95
```

**Comment by fbiville** [comment]
`-p` works interactively, and is used as follows:

1. liquigraph -c /my/changelog.xml -g jdbc:neo4j://my.host:7474 -u myUser -p
2. password will be prompted (and kept hidden)

If I understand well, you would like to have a non-interactive password parameter?

**Comment by fbiville** [comment]
If so, we could adapt step 1 to also support the following execution:

`echo "my_password" | liquigraph -c /my/changelog.xml -g jdbc:neo4j://my.host:7474 -u myUser -p`

It would require, afaik, just a little change to the shell script (sth like `if [ -t 0 ] _usual_ else read stdin fi`). I need to check the Batch counterpart.

What do you think? Would you like to push a change? :-)

**Comment by airomega** [comment]
Yeah - effectively I want to be able to do:
liquigraph -c /my/changelog.xml -g jdbc:neo4j://my.host:7474 -u myUser -p password

Happy to take a look at the code and contribute. I'm an recovering java dev and current go coder - it'll take me a while to set up a java env again :o)

**Comment by fbiville** [comment]
Just a JDK 7 and Maven 3.x is enough :-)
Feel free to reach me if you have any questions :+1:

**Comment by airomega** [comment]
To get my required functionality is a fairly small easy change.

The issue I raised relates to the annotation on the (password = true)  jcommander annotation on the password field in LiquigraphCli (doc:http://jcommander.org/#Types_of_options). If I remove the (password = true) it connects to neo4j and runs in using 

liquigraph -c /my/changelog.xml -g jdbc:neo4j://my.host:7474 -u myUser -p password

Obviously I don't want to push this in as it would likely break other peoples installations/setups. What would your preferred approach be? New flag?

**Comment by fbiville** [comment]
I need to dig a little more into JCommander sources to see if I can get a conditionally interactive parameter. I like the current password behaviour: password remains hidden and out of shell history. But your usecase is also 100% legit and we need a configurable behaviour for that.

**Comment by fbiville** [comment]
Good news: I found a way that requires no code change and does not compromise your password.
Just run:

```shell
 $> touch my_password.txt
# write your password there + chmod appropriately ;-)
 $> liquigraph -c /path/to/changelog.xml -g jdbc:neo4j://localhost:7474 -u my_user -p < my_password.txt
```

Would you like to send a Pull Request (see `gh-pages` branch) to update the documentation to reflect this?

**Comment by airomega** [comment]
Great. That works. Thanks for that.

I don't mind changing the documentation but I can't see it :D apologies it's probably in a really obvious place.

**Comment by fbiville** [comment]
The online documentation is [here](http://fbiville.github.io/liquigraph/).
The documentation sources are [here](https://github.com/fbiville/liquigraph/blob/gh-pages/index.html).

**Comment by airomega** [comment]
Cheers. Done. Let me know if there's any issues.

I'd be happy to include information on how we dockerized liquigraph too if wanted.

**Comment by fbiville** [comment]
Would you mind sending me a Twitter DM? I'm curious about what you did :-)
