### ISSUE TITLE
[Core] Allow repeatable / splitable queries for large migrations

### ISSUE THREAD

**Issue by fpavageau** [fbiville/liquigraph#77]
When migrating a large quantity of data, executing all the queries in a single transaction can lead to OutOfMemoryErrors in Neo4j.

I think this could be mitigated by repeating queries (using `LIMIT` to migrate batches) returning a single boolean value, like the pre-conditions. The query would be run until it returns `false`.

Another way could be to use separate "post-conditions" to validate whether the query needs to be repeated, to split the responsibilities.

**Comment by fbiville** [comment]
Could you show how it could look like, in terms of configuration? I'm not sure I understand well.

**Comment by fpavageau** [comment]
Let's say I have a graph with lots of nodes with `A` and `B` labels, linked via `CONTAINS_B` relationships, that I need to refactor to `LINKS_B` for some reason (e.g. better domain representation).

To migrate, I'd want to run
```
MATCH (a:A)-[r:CONTAINS_B]->(b:B)
CREATE (a)-[:LINKS_B]->(b)
WITH r
DELETE r
```
but given enough nodes and relationships, the transaction will be too large and result in a OOM.

So instead I could batch the migration with
```
MATCH (a:A)-[r:CONTAINS_B]->(b:B)
WITH a, r, b
LIMIT 1000
CREATE (a)-[:LINKS_B]->(b)
WITH r
DELETE r
```
and repeat it (in multiple transactions) until the post-condition / exit condition
```
OPTIONAL MATCH p=(:A)-[:CONTAINS_B]->(:B)
WITH p
LIMIT 1
RETURN p IS NULL AS result
```
returns `true`, i.e. only once all `CONTAINS_B` relationships have been migrated.

The changeset could look like:
```xml
<changeset id="contains-to-links" author="fpavageau">
  <query>
    MATCH (a:A)-[r:CONTAINS_B]->(b:B)
    WITH a, r, b
    LIMIT 1000
    CREATE (a)-[:LINKS_B]->(b)
    WITH r
    DELETE r
  </query>
  <postcondition if-not-met="REPEAT">
    <query>
      OPTIONAL MATCH p=(:A)-[:CONTAINS_B]->(:B)
      WITH p
      LIMIT 1
      RETURN p IS NULL AS result
    </query>
  </postcondition>
</changeset>
```
`if-not-met` could either be `REPEAT` (repeat on `true`, exit on `false) or `MARK_AS_EXECUTED` (exit on `true, repeat on `false`). Or maybe it's overkill, since it's just a matter of negating the result in the query, and it could be confusing when comparing with usage in preconditions where it has a slightly different purpose.

**Comment by fbiville** [comment]
I cannot think of a better way of handling this, so let's go for it!
I'm not sure why we'd need `MARK_AS_EXECUTED`, only `REPEAT` makes sense to me (and if there is only one option, do we need an explicit one?).

**Comment by fpavageau** [comment]
`MARK_AS_EXECUTED` could be used to end after the execution *unless* the postcondition returns `false`, but OK, it's overkill 😄 (and not available for preconditions). So no, we don't need to specify an `if-not-met` attribute with a single possible value.

**Comment by fbiville** [comment]
Feel like pushing a PR for this? :-)

**Comment by fpavageau** [comment]
I can probably do that, yes. Let's see if I can start working on that on Wednesday.

**Comment by fbiville** [comment]
I guess that's the last standing issue before RC4 :-)

**Comment by fpavageau** [comment]
I needed #70 more than this one, which is why I prioritized it yesterday. 😃

You're the PO, you get to decide if it's necessary for RC4 and ultimately 1.0. I can probably start working on this issue next Wednesday, not sure if it can happen before. I know I already wrote that 10 days ago. 😄

Also, it needs both code and documentation, so it's going to take a bit longer than my previous contributions.

**Comment by fbiville** [comment]
We can split the work maybe, I can help ;-)

**Comment by fpavageau** [comment]
I'm working on the issue right now, and I've realized I need a change which is probably reasonable, but changes some undocumented semantics of preconditions: currently the preconditions are run in the same transaction as the actual queries, which is then committed at the end; it means a precondition query could actually modify the data itself, and that would be committed.

To implement the repeatable queries using postcondition, I need to repeatedly run transactions executing the migration query then the postcondition query, until the postcondition returns `false`. That means I should move the precondition execution to a first, separate transaction. Should we take that as the opportunity to document that preconditions cannot modify data, and actually rollback that transaction?

**Comment by fbiville** [comment]
@fpavageau sounds like a very reasonable change to me: :+1:

**Comment by fbiville** [comment]
I guess that's what you planned but can you make sure to change the precondition execution in a separate commit? Thanks!

**Comment by fbiville** [comment]
Great stuff, everything is merged and documented!!
