### ISSUE TITLE
[Core] Allow nested changelogs

### ISSUE THREAD

**Issue by fbiville** [fbiville/liquigraph#8]
Currently, all changesets have to be declared within the same changelog.
Allowing nested changelogs would allow to organize changesets as users see fit, e.g. per software release.

**Comment by fbiville** [comment]
FYI: http://stackoverflow.com/questions/28078198/custom-xml-processing-with-jaxb.

**Comment by fbiville** [comment]
Cool, Hazelcast does the same: https://github.com/hazelcast/hazelcast/blob/e7dc993c34f23b425451e6d39f780e0515a9080f/hazelcast/src/main/java/com/hazelcast/config/AbstractConfigBuilder.java#L66.

**Comment by sim51** [comment]
It's work for me
