### ISSUE TITLE
[Core] Define rollback in changeset

### ISSUE THREAD

**Issue by airomega** [fbiville/liquigraph#86]
It's feasible a release may not go to plan when deploying large applications with many dependencies. In these cases it's likely that the application will be 'rolled back' to bring the application up again as quickly as possible. It would be useful to have a roll-back feature in Liquigraph that allows users to revert the database to a previous state.

**Comment by fbiville** [comment]
Closing it for now. Feel free to reopen it if you have a clear idea about how this should work.
