### ISSUE TITLE
[Core] Manage ResultSets consistently in master_3.x

### ISSUE THREAD

**Issue by fpavageau** [fbiville/liquigraph#95]
While applying the postcondition commits onto `master_3.x`, I noticed that in some tests (e.g. `ChangelogGraphWriteTestSuite`, `ResultSets` have been moved out of the try-with-resources declaration and into the body, which would seem to indicate they shouldn't be closed anymore.

However, in other tests (e.g. `LiquigraphTestSuite`), they remain in the try-with-resources declaration.

Should it be done consistently across test (and maybe production) code?

**Comment by fbiville** [comment]
Yep, this is due to https://github.com/neo4j-contrib/neo4j-jdbc/issues/51 (which is solved in a later version). We should be consistent indeed (and watch new releases :P).

**Comment by fbiville** [comment]
Fixed via https://github.com/fbiville/liquigraph/commit/8d9f7b454870dabf64fef063f7f4a0cbaf16a780.
