### ISSUE TITLE
[Core] Enable usage of DataSource instead of URL/Username/Password

### ISSUE THREAD

**Issue by mvitz** [fbiville/liquigraph#98]
I'm using liquigraph inside a spring-boot application. Normally you are given an already defined `java.sql.DataSource` which you can use to obtain a connection. Unfortunately liquigraph doesn't support this. Therefore I'm currently using a hack to get the URL/Username/Password and providing this to liquigraph.

**Comment by fbiville** [comment]
You are right, I should provide this way as well!

**Comment by fbiville** [comment]
First draft [here](https://github.com/fbiville/liquigraph/pull/100). Open for early feedback ;-)

**Comment by fbiville** [comment]
Status:

 - [x] tests, tests, tests
 - [ ] documentation
 - [ ] `master_3.x`

**Comment by mvitz** [comment]
I just checked the implementation and found a small issue that prevents me from using this in the Spring-Boot module.

The DataSource is configured to be in autoCommit-mode by default. Liquigraph should set this to false after retrieving a connection from the DataSource and restore the original autoCommit value when the connection is closed.

**Comment by fbiville** [comment]
Thanks for the report. If the connection is closed, is there an actual need to restore its autocommit flag?

**Comment by mvitz** [comment]
Normally not, but in case of a connection pool a closed connection often is just returned to the pool and reused. Resetting the original state prevents some subtle bugs.

**Comment by fpavageau** [comment]
The additional commits have now been merged in `master_3.x`, with the dependency on the newly released 3.0.1 driver.

**Comment by fbiville** [comment]
Releases have been done, so I guess this issue can be closed.
Feel free to reopen @mvitz if you find something odd.
